package org.autorepair.data.exceptions

class UnauthorizedException: Throwable(message = "no auth")